oddbird/Metecho

metashare/api/gh.py
metashare/api/jobs.py
metashare/api/tests/gh.py
metashare/api/tests/jobs.py

Ignore branch name, it's wrong.
See https://github.com/SFDO-Tooling/MetaShare/pull/238

[recreated-deleted-branch] Move GitHub concerns into GitHub module

---

config/settings/base.py
metashare/api/sf_run_flow.py

@wlonk turns out I do need a fix soon because I was also wrong about the name of the field we need to set.

Fix signup instance setting

---

hooks/pre-commit

[speed-pre-commit] Speed pre-commit hook

---

metashare/api/sf_run_flow.py

[set-scratch-org-days] Make all scratch orgs live 30 days

---

requirements/dev.in
requirements/dev.txt
requirements/prod.in
requirements/prod.txt

📦 Update all Python dependencies

---

requirements/dev.in
requirements/dev.txt
requirements/prod.in
requirements/prod.txt

📦 Update Python dependencies

---

metashare/api/validators.py
requirements/dev.in
requirements/dev.txt
requirements/prod.in
requirements/prod.txt

Update all Python dependencies.

Python dependency upgrades

---

requirements/dev.in
requirements/dev.txt
requirements/prod.in
requirements/prod.txt

[py-updates] Update Python dependencies

---

metashare/api/hook_serializers.py
metashare/api/tests/hook_serializers.py

[ease-up-webhook-errors] Tone down tag-related webhook warnings

---

requirements/dev.txt
requirements/prod.in
requirements/prod.txt

📦 Add omnibus Python dependencies update

---

.circleci/config.yml
.dockerignore
.eslintignore
.gitignore
.prettierignore
.stylelintignore
package.json
yarn.lock

Try out packtracker.io for analyzing Webpack bundle.

---

requirements/dev.in
requirements/dev.txt
requirements/prod.in
requirements/prod.txt

[py-deps-update] Omnibus Python dependencies update

---

metashare/api/admin.py
metashare/api/jobs.py
metashare/api/tests/admin.py

This enforces it at the level of admin-site validation. It won't change existing data.

[admin-site-validation] Enforce that Site.domain be a bare domain

---

metashare/api/sf_org_changes.py

[fix-create-org] Make latest_revision_numbers serializable for scheduler

---

.circleci/config.yml

Make packtracker on CI conditional on PT_PROJECT_TOKEN env var.

---

metashare/api/jobs.py
metashare/api/sf_run_flow.py
metashare/api/tests/views.py
metashare/api/views.py
src/js/components/tasks/cards/footer.tsx

[refresh-fixes] Fix up how org refresh is handled

---

requirements/prod.in
requirements/prod.txt

This fixes a problem when deploying packages that are stored in sfdx format.

📦 Switch cumulusci to master

---

metashare/api/models.py
metashare/api/tests/models.py

Strip access token out of ScratchOrg config on save

---

metashare/api/sf_run_flow.py

Set expires days correctly everywhere

---

CONTRIBUTING.rst

Add documentation on the connected GitHub app

---

CONTRIBUTING.rst

More doc cleanup.

---

config/settings/base.py
requirements/dev.txt
requirements/prod.in
requirements/prod.txt

Make sure we can restrict most of the site to specified IP ranges but keep the webhook endpoint open.
Also update sfdo-template-helpers (which adds support for this setting) and cumulusci (since there's a new release yesterday)
p.s. hey look, you can end up with duplicate emojis if you use git amend

📦 📦 Make sure webhooks aren't IP-restricted

---

config/settings/base.py

Sorry for the multiple PRs; I forgot we didn't have a way to set RESTRICTED_PREFIXES from a config var yet.

get RESTRICTED_PREFIXES from env var

---

metecho/api/jobs.py
metecho/api/models.py
src/js/components/tasks/detail.tsx
test/js/components/tasks/detail.test.jsx

https://trello.com/c/7ZhhbEaT
---

Hotfix repo bug; only show "check for changes" after dev org has been viewed.

---

src/js/components/commits/list.tsx
src/js/components/tasks/table.tsx
src/sass/components/_history.scss
src/sass/patterns/_data-tables.scss

https://trello.com/c/AEzmtH3A
_Provide URLs and/or a description of where to look._
---

Hotfix task list table width.

---

requirements/prod.in
requirements/prod.txt

Fix slug length issue by using latest sfdo-template-helpers

---

requirements/dev.in
requirements/dev.txt
requirements/prod.in
requirements/prod.txt

Update Python dependencies

---

README.rst
metecho/api/sf_run_flow.py

sfdx supports this so we should too

Handle scratch org features as a single string

---

metecho/api/gh.py
metecho/api/management/commands/populate_data.py
metecho/api/migrations/0016_add_socialapps.py
metecho/api/tests/jobs.py
metecho/tests/logfmt.py
requirements/dev.in
requirements/dev.txt
requirements/prod.in
requirements/prod.txt

Update all Python dependencies

---

metecho/api/hook_serializers.py
metecho/api/jobs.py
metecho/api/models.py
metecho/api/tests/gh.py
metecho/api/tests/hook_serializers.py
metecho/api/tests/models.py
metecho/api/tests/views.py

https://trello.com/c/mykQfEsb
1. Enable GH webhooks locally (see `CONTRIBUTING.md`)
2. Create a new Task.
3. Create an Org on that task to trigger branch-creation.
4. Go to the task branch (on https://github.com/oddbird/Metecho-Test/) and make a new commit directly from GitHub.
5. See the commit appear in Metecho, along with the ability to Submit for Review.
6. Create a PR for that branch, again directly from GitHub.
7. See the "Submit for Review" btn disappear, and the "View Pull Request" button …

Handle Task commits (and Task/Project PR events) coming directly from GitHub.

---

metecho/api/jobs.py

Only store logs if we have them

---

metecho/urls.py

Use allowed-list of routes to pass through to JS route-handler instead of catch-all.

---

.circleci/config.yml
Dockerfile
config/settings/base.py
docker-compose.yml
metecho/api/sf_run_flow.py

Address review; pin back redis/postgres versions.

---

src/stories/pages/404.stories.mdx
src/stories/pages/404.stories.tsx

https://trello.com/c/f0jSvig0/93-metecho-404
Adds general explanatory documentation to the 404 component. 
- [x ] Description is in Trello card
_Please explain how to best reproduce the issue and/or test the changes locally (including the pages/URLs/views/states to review)._
Documention currently lies in the "Intro" section under the 404 component

[storybook] 404

---

metecho/api/tests/serializers.py
metecho/api/validators.py

https://trello.com/c/3Czetbio/256-bug-error-adding-github-collaborators

Compare GH users by ID, not full object.

---

.storybook/main.js
.storybook/preview.js
src/js/components/404.tsx
src/stories/commits/CommitList.stories.mdx
src/stories/commits/CommitList.stories.tsx
src/stories/epics/EpicTable.stories.mdx
src/stories/epics/EpicTable.stories.tsx
src/stories/epics/createForm.stories.mdx
src/stories/epics/createForm.stories.tsx
src/stories/fixtures.ts
src/stories/pages/404.stories.mdx
src/stories/pages/404.stories.tsx
src/stories/tasks/TasksTable.stories.mdx
src/stories/tasks/TasksTable.stories.tsx

- https://oddbird.slack.com/archives/CH6EN9NMA/p1611858382018100
- Use "Docs" and "Example[s]" as headings
- Remove confusing controls, and replace with multiselects where helpful
- Remove "Docs" tab from component pages (we're using MDX as a replacement)

Various storybook cleanup

---

config/settings/base.py
metecho/api/__init__.py

See: https://docs.djangoproject.com/en/3.2/releases/3.2/

Fix Django warning

---

metecho/api/admin.py
src/js/components/tasks/table.tsx
src/stories/fixtures.ts
src/stories/tasks/TasksTable.stories.tsx
test/js/components/epics/detail.test.jsx

- https://trello.com/c/4PgrXB0t/275-as-a-user-especially-without-write-access-i-want-to-see-a-status-of-test-in-the-task-list-view-so-that-i-know-when-a-tester-is-n
_Please explain how to best reproduce the issue and/or test the changes locally (including the pages/URLs/views/states to review)._
- tasks table

Add "Test" status in tasks table.

---

src/sass/components/_path.scss

Quick CSS update for inheriting colors when possible, and removing unnecessary lines.
Story: https://trello.com/c/AOzuvbgC/283-path-colors-quick-fix

[path-colors] Update path color css

---

metecho/api/admin.py

https://trello.com/c/ocDP15n7/290-improve-admin-search-and-filters
Visit the admin and search/filter away on all models!

Use more admin filters and search fields

---

metecho/api/models.py
metecho/api/tests/models.py

Visit the admin detail page for Projects, Epics, and Tasks. You should now see a "View on site" link in the upper right corner.

Add "View on site" links to admin

---

.circleci/config.yml

Deploy Storybook from CI

---

package.json
yarn.lock

upgrade nested-property

---

metecho/api/jobs.py
metecho/api/models.py
metecho/api/push.py
metecho/api/serializers.py
src/js/components/epics/table/index.tsx
src/js/store/epics/actions.ts
src/js/store/epics/reducer.ts
src/js/store/tasks/actions.ts
src/js/store/tasks/reducer.ts
src/js/utils/websockets.ts
test/js/store/epics/actions.test.js
test/js/store/epics/reducer.test.js
test/js/store/tasks/actions.test.js
test/js/store/tasks/reducer.test.js
test/js/utils/websockets.test.js

_Please explain how to best reproduce the issue and/or test the changes locally (including the pages/URLs/views/states to review)._
- Open two browser tabs to the same project
- Create a new Epic or Task in one tab, and see it appear in the other tab
- Delete an Epic or Task in one tab, and see it disappear in the other tab

Add newly-created tasks/epics via ws events.

---

src/js/components/tasks/steps.tsx

https://oddbird.slack.com/archives/CB2576XT4/p1637209222019300

Do not show "Retrieve changes" as clickable action except for Dev user.

---

config/settings/base.py
metecho/api/jobs.py
metecho/api/migrations/0103_alter_task_status.py
metecho/api/models.py
metecho/api/serializers.py
metecho/api/tests/hook_serializers.py
metecho/api/tests/jobs.py
metecho/api/tests/models.py
metecho/api/tests/serializers.py
metecho/api/tests/views.py
metecho/api/views.py

The built-in choices from Django provide proper autocompletion when comparted against the previous `Choices` implementation. I wanted to make this change before working on upcoming stories that will create more choices.

Switch to Django model choices

---

CONTRIBUTING.rst

Add org member permissions to docs

---

config/settings/base.py

Fix missing GitHub account tokens

---

.github/dependabot.yml
.github/setup-docker-compose/action.yml
.github/workflows/upgrade-deps.yml
Dockerfile
package.json
requirements/dev.in
requirements/prod.in

Add upgrade-deps gh workflow.

---

CONTRIBUTING.rst
Dockerfile
src/js/components/githubUsers/assignTaskRole.tsx
src/js/components/orgs/taskOrgCard.tsx
src/js/components/tasks/table.tsx
test/js/components/githubUsers/assignTaskRole.test.jsx
test/js/components/orgs/taskOrgCards.test.jsx

Task with Epic:
Task without Epic:

Do not show text about Epic Collaborators for epic-less Task.
