CONTRIBUTING.rst
metashare/api/jobs.py
metashare/api/tests/jobs.py

N/A
This resolves a bug where new scratch orgs were being provisioned from (and flows run on) the default repo branch instead of the latest task branch. See explanation in https://oddbird.slack.com/archives/CB2576XT4/p1571327862114600?thread_ts=1571182294.098200&cid=CB2576XT4
1. Create Dev scratch org. It should show "Status: up-to-date"
2. Click "View Org" to open the org.
3. Click the "Object Manager" tab.
4. Click "Contact"
5. Click "Fields & Relationships" on the left.
6. Click the "New" button. …

[fix-org-branch] Create orgs from latest task branch, not default repo branch.

---

src/js/store/repositories/reducer.ts
test/js/store/repositories/reducer.test.js

https://trello.com/c/ROtqxOLK
For most objects in the front end store, we want to wipe and force a refetch after the WS channel disconnects/reconnects. This ensures that any models are up-to-date, and that the new WS channel subscribes to the models appropriately.
For repositories this was overkill, both because it was not properly refetching them anyway, and also because they seldom change and we do not subscribe to them via WS.
- Run the django server and webpack server in separate processes (e.g. …

[no-empty-repos-list] No need to refresh repos list after WS disconnect/reconnect.

---

metashare/api/sf_run_flow.py

This is needed in order to use some new scratch org settings.

Update to the newest version of the API

---

metashare/api/serializers.py
metashare/api/tests/serializers.py

I found a stupid-hack way to get the error messages onto the right field. It's surprisingly low-impact!

[well-named-errors] Report name errors as coming from the name field.

---

CONTRIBUTING.rst
metashare/api/sf_run_flow.py

This is in aid of getting makemessages to gather them correctly. It cannot see anything but single string literals inside gettext calls.
I would love another set of eyes to make sure I'm not missing other backend-generated user-facing errors we should be able to translate.

[fix-backend-gettext] Use more string literals for user-facing errors

---

compose/web/start-server.sh
config/settings/base.py

This is a stop-gap measure to allow automatically restarting the server in development. In production, we don't have this issue, so that's good.  The error appeared to be arising not directly from any code we had written, and I had no luck isolating it to one component (Sentry, New Relic, the websocket consumer, and possibly other components were all candidates), so I opted to suppress the warning and allow restart in dev, instead.
Also, incidentally, I think we can drop the branch-name in PR title thing? GitHub has made the branch name a bit more visible and accessible since we started that, so I think it doesn't matter as much anymore, for me at least.

Suppress sync warnings in Django restart

---

CONTRIBUTING.rst
hooks/pre-commit
package.json

The key thing here is to install the latest Docker Desktop, so you'll have `docker-compose` at least version `1.25.2`. There are a few small related tweaks in here.

[improve-hook-reliability] Require reuse-running containers to be connectable

---

src/js/components/tasks/cards/card.tsx
src/js/components/tasks/cards/orgActions.tsx
src/js/components/tasks/cards/submitReview.tsx
src/sass/components/_org-cards.scss

Was a part of this story: https://trello.com/c/BegMDQLo/58-facilitate-qa-results-submission-through-metashare-and-github-commit-status but waited until after merge to fix
Allowed the nested card to wrap instead of truncating the heading "Review Org"
You can test once you, as the reviewer, has already submitted a review, then deleted the org. That is when 2 buttons will appear in the header of that Reviewer Card
_Provide URLs and/or a description of where to look._
Task detail page
_Provide …

force wrapping on nested cards

---

metashare/api/models.py
metashare/api/templatetags/api_bootstrap.py
metashare/api/tests/models.py
metashare/api/views.py

We've occasionally gotten db integrity errors for GitHubRepository duplicates which I think may happen if multiple concurrent runs of user.refresh_repositories get triggered for the same user. This attempts to avoid queuing a refresh if one is already in progress.

Avoid concurrent runs of refresh_repositories

---

requirements/prod.in
requirements/prod.txt

The main point of this is to remove the unused requirement of django-filters
The other changes are from the update to cumulusci; I'm not sure why some of its dependencies were missing from the lockfile before.

📦 Re-lock Python; remove django-filters which is not the same as django-filter

---

CONTRIBUTING.rst
metashare/management/commands/promote_superuser.py
metashare/management/commands/tests/promote_superuser.py

Like it says on the tin. It can be hard to remember which email from a github account is the default.

Promote superusers by username rather than email

---

Procfile
Procfile_worker_short
package.json
requirements.txt
requirements/prod.in
requirements/prod.txt

Add a Procfile to make it possible to do a non-container deployment to Heroku.
We've run some issues with the container stack:
- intermittent "blob not found" errors while pushing to the heroku container registry
- private space apps don't honor the `run` section of heroku.yml for some reason https://help.heroku.com/RNIC7H18/why-my-private-spaces-app-on-container-registry-runtime-ignores-heroku-yml
- it also seems to take longer to build using the Dockerfile

Add a Procfile

---

config/settings/test.py
metecho/api/gh.py
metecho/api/tests/gh.py

In order to prevent execution of code that we haven't reviewed, this adds a check to confirm that cumulusci.yml is unchanged from master.

make sure cumulusci.yml hasn't changed from master

---

metecho/api/admin.py
metecho/api/gh.py
metecho/api/sf_org_changes.py
metecho/api/tests/admin.py
metecho/api/tests/gh.py

This contains 2 unrelated fixes:
1. Trying to verify existence of a private repository gets a 404 even if it exists if we have not authenticated as the github app's _specific installation for that repo_. This means we don't have a good way to distinguish between repos that don't exist and repos that we can't see, so I consolidated the checks in RepositoryForm.clean
2. When committing retrieved changes, only look for files to commit in the target directory, not the entire project. This will help avoid picking up changes in .sfdx even if the CommitDir util from cumulusci isn't truly honoring .gitignore yet.

Fixes for private repos and which files to commit

---

metecho/api/models.py

Avoid possible XSS injection (this content shouldn't be user-sourced and should be delivered as a text/plain email, but security asked us to do this anyway as a security-in-depth measure)

Sanitize email content to prevent XSS injection

---

src/js/components/user/githubUser.tsx
test/js/components/projects/detail.test.jsx

https://trello.com/c/Dfl03CRc
Alert Assignee Modal in:
Project Detail -> Assign user from Task Table &
Task Detail -> Assign user from Org Card

[bugfix] I do not want it to auto-toggle sending assignment email alert

---

metecho/api/jobs.py

@davisagli This explicitly reverts the changes made in SFDO-Tooling/Metecho/pull/333 -- let me know if you prefer a different solution.

Re-add branch and commit to project_config when fetching task config names.

---

metecho/api/jobs.py
metecho/api/tests/jobs.py

https://trello.com/c/Jtur1CJp/
If you don't care about losing your database content, the easiest way to test is `python manage.py truncate_data` and `python manage.py populate_data`.  This will clear all `Project`s and fetch fresh images when re-populating.
Otherwise you will need to manually clear `Project.repo_image_url` and save, which will trigger the corresponding job and after a few seconds you should have the right image, or nothing if the repo hasn't set one manually.
Repos without manually-set images will get a generic icon instead of the og:image generated by GitHub. In this screenshot only Metecho-Test has a manually-set image

Only store manually-set repository images

---

src/js/index.tsx
src/sass/patterns/_containers.scss
templates/404.html

Wanted to remove the unecessary horizontal scroll.
View a task or epic page that scrolls vertically. See if horizontal scrollbar is also present.
Screenshot on top shows the "after" view, bottom is before
.

[remove-scroll] Use % instead of vw for container

---

metecho/api/migrations/0040_task_status.py
metecho/api/migrations/0054_task_review_status.py
metecho/api/migrations/0061_fix_project_status.py
metecho/api/migrations/0083_remove_all_null_strings.py
metecho/api/migrations/0103_alter_task_status.py
metecho/api/models.py

Follow up to #1808. This removes a lot of the repetition on the choices. The changes to the migrations are for the human-readable names displayed in the admin (the second value of the tuple), the actual DB values remain the same.

Simplify model choices

---

config/settings/base.py
config/settings/production.py

We'll see if this works once we deploy to Heroku

Fix django-rq config for SSL Redis

---

config/settings/base.py
config/settings/production.py
metecho/redis.py
metecho/tests/redis.py

It looks like Django's Redis cache backend only accepts 4 options: [serializer, pool_class, db, and parser_class](https://github.com/django/django/blob/stable/4.0.x/django/core/cache/backends/redis.py#L35-L38). What we want to do is set the [`ssl_cert_reqs` kwarg](https://github.com/redis/redis-py/blob/64791a5/redis/connection.py#L832) of SSLConnection to `None`. Ideally Django would provide a way to pass connection kwargs all the way from settings but that's not the case, so we need to override the pool class instead.

Use a custom connection pool in production

---

.github/workflows/deploy-storybook.yml

Restore the job that deploys to Storybook that was lost when migrating from CircleCI
From https://github.com/oddbird/Metecho/pull/2149#discussion_r865138094

Restore deploy-storybook job

---

.github/workflows/deploy-storybook.yml
.github/workflows/test.yml

https://github.com/storybookjs/storybook-deployer/issues/77

Set GH_TOKEN on deploy-storybook job

---

src/sass/patterns/_form-elements.scss

Layout would break when expanding ignored changes accordion in the retrieve changes modal. 
**Before and After**
- Make a dev org on a task or use existing one if you have one
- Make some changes to the org (see pinned instructions if you don't know how in Slack). 
- Open the "Retrieve Changes from Dev Org" modal
- Leave the first screen on the default selection and choose "Save & Next"
- Then select a checkbox from the All changes list and choose "Ignore Selected Changes"
- Expand the Ignored changes if they weren't already and see if the spacing looks correct.
https://trello.com/c/cbaMfIcq/362-layout-breaks-when-expanding-ignored-changes-accordion

fix nested accordion padding

---

.github/workflows/deploy-storybook.yml
Dockerfile

A few things we picked up from our recent work on MetaDeploy:
- Move the installation of `sfdx-cli` higher up in the `Dockerfile` so that layer is cached
- Read the node version from `.nvmrc` instead of using regex in `deploy-storybook` workflow

Misc cleanup
